---
name: 📦 Build Appliance electon app
on:
  push:
#    branches: [ "main"]
#    paths:
#      - 'appliance-application/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'appliance-application/**'


jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: appliance-application


      - name: Build
        run: npm run compile
        working-directory: appliance-application

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: appliance-application-${{ matrix.os }}
            path: appliance-application/dist